public class WorkControlConstants {
	public static final String Pending = 'Pending';
	public static final String Fail = 'Fail';
	public static final String Success = 'Success';
	public static final String PendingReprocessing = 'Pending Reprocessing';
	public static final String Processing = 'Processing';
	public static final String Disabled = 'Disabled';

	public static final String Deferred = 'Deferred';
	public static final String Immediate = 'Immediate';
	public static final String ImmediateCallout = 'Immediate Callout';
}