//Contém as regras de comissionamento da área de Produtos financeiros

public class ComissaoProdFinanceirosCommand implements IFluxoComissao {

    public ComissaoSchema.TipoComissao definirTipoComissao(ComissaoSchema.ComissaoContext context) { 
        return null;
    }

    public List<Comissionado__c> encontrarComissionados(ComissaoSchema.ComissaoContext context) {
        //TODO: IMPLEMENTAR REGRAS

        return null;
    }
}